import { slugify } from './scaffold.js';

export const STACKS = {
  typescript: { label: 'TypeScript / JavaScript', app: 'TypeScript 5 + Node 22 (or Bun)', ui: 'React 18 + Vite', api: 'Hono (lightweight, edge-ready)', data: 'SQLite via better-sqlite3 → Postgres when needed', test: 'Vitest', lint: 'Biome', why: 'Strong typing, one language across CLI + web.' },
  python:     { label: 'Python',                   app: 'Python 3.12 + uv',                 ui: 'Starlette + server-rendered templates', api: 'FastAPI', data: 'SQLite via stdlib sqlite3 → Postgres when needed', test: 'pytest', lint: 'Ruff', why: 'Fast to iterate, rich stdlib for parsing and data work.' },
  go:         { label: 'Go',                        app: 'Go 1.22',                          ui: 'net/http + static assets', api: 'net/http stdlib (or chi)', data: 'SQLite via modernc.org/sqlite → Postgres when needed', test: 'go test', lint: 'golangci-lint', why: 'Single static binary, trivial to deploy.' },
  rust:       { label: 'Rust',                      app: 'Rust 2021 edition',                ui: 'axum + serve static', api: 'axum', data: 'rusqlite → Postgres via sqlx when needed', test: 'cargo test', lint: 'clippy', why: 'Maximum correctness; compile-time safety.' },
  unsure:     { label: 'Not sure yet',              app: 'TypeScript 5 + Node 22',           ui: 'React 18 + Vite', api: 'Hono', data: 'SQLite via better-sqlite3', test: 'Vitest', lint: 'Biome', why: 'Recommended default: one language, huge ecosystem, fastest path to a working demo.' },
};

export const PROJECT_TYPES = {
  tool:          'CLI / developer tool',
  'web-app':     'Web app',
  service:       'API / service',
  'data-pipeline': 'Data pipeline',
  unsure:        'Not sure yet',
};

export const TEAM_SIZES = {
  solo:        'Solo',
  pair:        'Pair',
  'small-team':'Small team (3–5)',
};

export function downloadFile(name, content, type = 'text/markdown;charset=utf-8') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = name;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function buildBriefMarkdown(record) {
  // Use the canonical brief object when available (new records), otherwise fall
  // back to reading form fields directly from the record (legacy history records
  // where outputs.brief is still a plain string).
  const briefObj = (record.outputs?.brief && typeof record.outputs.brief === 'object')
    ? record.outputs.brief
    : null;

  const stackLabel = briefObj
    ? briefObj.stackLabel
    : (record.customStack ? record.customStack : (STACKS[record.stack] || STACKS.unsure).label);

  const idea        = briefObj ? briefObj.idea        : (record.idea     || '—');
  const projectType = briefObj ? briefObj.projectType : (PROJECT_TYPES[record.type] || record.type || '—');
  const teamSize    = briefObj ? briefObj.teamSize    : (TEAM_SIZES[record.team]    || record.team  || '—');
  const audience    = briefObj ? briefObj.audience    : (record.audience  || '—');
  const github      = briefObj ? briefObj.github      : (record.github    || '—');
  const deadline    = briefObj ? briefObj.deadline    : (record.deadline  || '—');
  const comfort     = briefObj ? briefObj.comfort     : (record.comfort   || '—');
  const ownerName   = briefObj ? briefObj.ownerName   : (record.name      || 'Project');

  const L = [
    `# ${ownerName} — AbridgeAI Project Brief`,
    '',
    `> Generated by AbridgeAI · ${record.time || new Date().toLocaleString()}`,
    '',
    '## Project Overview',
    '',
    `- **Idea:** ${idea}`,
    `- **Stack:** ${stackLabel}`,
    `- **Type:** ${projectType}`,
    `- **Team:** ${teamSize}`,
    `- **Audience:** ${audience}`,
    `- **GitHub:** ${github}`,
    `- **Deadline:** ${deadline}`,
    `- **Comfort level:** ${comfort}`,
    '',
  ];

  if (record.outputs) {
    // For the brief body, extract plain text from either shape.
    const briefBody = briefObj
      ? briefObj.text
      : (typeof record.outputs.brief === 'string' ? record.outputs.brief : null);

    const sections = [
      ['1. Builder Signals (GitHub Analysis)', record.outputs.github?.text],
      ['2. Research & Opportunity Analysis',   record.outputs.research],
      ['3. Feasibility Assessment',            record.outputs.feasibility?.text],
      ['4. Architecture Direction',            record.outputs.architecture],
      ['5. Tech Stack Recommendation',         record.outputs.stack],
      ['6. Builder Plan & Starter Scaffold',   record.outputs.builder?.text],
      ['7. Implementation Plan',               briefBody],
    ];
    sections.forEach(([title, body]) => {
      if (!body) return;
      L.push(`## ${title}`, '', '```text', body, '```', '');
    });
  }
  return L.join('\n');
}
